# **Pytorch Operations**

Accessing the tensor data, slicing it, editing the data and performing various mathematical operations on it.


In [2]:
import torch
print(torch.__version__)

1.4.0


***Accessing tensor data***

Data inside tensors can be accessed using indexing or slicing.

In [22]:
x = (torch.rand((2,3,4))*100).int()
print(x)

print(x[1][2])
print(x[0][1][2], x[0][1][2].item()) # Gets the data as tensor by default. In order to get Python number from tensor, use .item()


print(x[:, 1, :3]) # Use slicing to get ranges of values from tensor by :, like in numpy arrays.
print(x[1, 2])
print(x[..., 2])

tensor([[[85, 14, 48, 98],
         [70, 61, 14, 77],
         [42, 54, 86, 39]],

        [[15, 60,  4, 11],
         [20, 91, 60, 45],
         [18, 20,  4, 35]]], dtype=torch.int32)
tensor([18, 20,  4, 35], dtype=torch.int32)
tensor(14, dtype=torch.int32) 14
tensor([[70, 61, 14],
        [20, 91, 60]], dtype=torch.int32)
tensor([18, 20,  4, 35], dtype=torch.int32)
tensor([[48, 14, 86],
        [ 4, 60,  4]], dtype=torch.int32)


***Casting PyTorch tensor to another type***

By default PyTorch tensors are FloatTensors. Having said that, we can convert/cast the tensors between various types.

In [13]:
def_tensor = torch.rand((2,3)) # By default, Pytorch tensors are FloatTensor. torch.Tensor is an alias for the default tensor type (torch.FloatTensor).
print(def_tensor)
print(type(def_tensor))

int_def_tensor = def_tensor.int() #Casts float tensor to int using int(), but we are losing information here.
print(int_def_tensor)

int_def_tensor = (def_tensor*100).int() #Multiply the tensor with 100, gets us some data,, and then when we cast it to int(),, we still have some info.
print(int_def_tensor)

tensor([[0.7585, 0.4014, 0.2297],
        [0.8760, 0.6446, 0.4661]])
<class 'torch.Tensor'>
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[75, 40, 22],
        [87, 64, 46]], dtype=torch.int32)


torch.Tensor

***Converting Pytorch tensor to list/Reshaping tensors***



In [49]:
x = (torch.rand(2,3,2)*100).int()
print(x)

print(x.flatten()) # Returns a tensor with all values collapsed into 1-dimension. use .tolist() to convert the tensor to a python list.
print(x.flatten().tolist())
print(x.tolist()) #Converts the tensor to list of same rank as tensor



tensor([[[12, 71],
         [25, 21],
         [54, 86]],

        [[19, 78],
         [36, 64],
         [83, 49]]], dtype=torch.int32)
tensor([12, 71, 25, 21, 54, 86, 19, 78, 36, 64, 83, 49], dtype=torch.int32)
[12, 71, 25, 21, 54, 86, 19, 78, 36, 64, 83, 49]
[[[12, 71], [25, 21], [54, 86]], [[19, 78], [36, 64], [83, 49]]]


In [57]:
x = (torch.rand(2,4,4)*100).int() 
print(x) #Tensor of 2x4x4
print(x.view(-1)) # Returns a 1-dimensional view of the data - 1x32
print(x.view(-1,4)) #Returns a rank2 tensor with 4 elements in the last dimension - 8x4
print(x.view(-1,2,4)) #Returns a rank3 tensor with 4 elements in the last dimension, and 2 elements in last-but-one dimension - 4x2x4
print(x.view(4,2,4)) #Same as above in this case. -1 denotes all remaining - 4x2x4

print(x.view(4,-1)) #Returns a rank2 tensor with 4 in the 1st dimension - 4x8
print(x.view(2,2,2,-1)) #Returns a rank4 tensor - 2x2x2x4

tensor([[[19, 60, 61, 61],
         [38, 51, 22, 18],
         [92, 55, 45, 54],
         [52, 14, 16, 44]],

        [[21, 92,  8, 29],
         [66, 24, 98, 18],
         [ 6,  0, 25,  9],
         [80, 45, 32, 36]]], dtype=torch.int32)
tensor([19, 60, 61, 61, 38, 51, 22, 18, 92, 55, 45, 54, 52, 14, 16, 44, 21, 92,
         8, 29, 66, 24, 98, 18,  6,  0, 25,  9, 80, 45, 32, 36],
       dtype=torch.int32)
tensor([[19, 60, 61, 61],
        [38, 51, 22, 18],
        [92, 55, 45, 54],
        [52, 14, 16, 44],
        [21, 92,  8, 29],
        [66, 24, 98, 18],
        [ 6,  0, 25,  9],
        [80, 45, 32, 36]], dtype=torch.int32)
tensor([[[19, 60, 61, 61],
         [38, 51, 22, 18]],

        [[92, 55, 45, 54],
         [52, 14, 16, 44]],

        [[21, 92,  8, 29],
         [66, 24, 98, 18]],

        [[ 6,  0, 25,  9],
         [80, 45, 32, 36]]], dtype=torch.int32)
tensor([[[19, 60, 61, 61],
         [38, 51, 22, 18]],

        [[92, 55, 45, 54],
         [52, 14, 16, 44]],

       

***Minimum/Maximum of tensor data***

To identify the minimum/maximum of values of tensor data



In [28]:
x = (torch.rand(2,3,4)*100).int()
print(x)

print(torch.min(x), torch.max(x), torch.min(x).item(), torch.max(x).item()) #Returns a 0-dimensional tensor with just one element. We should use .item() to return a Python number from the tensor.


tensor([[[40,  0, 96, 34],
         [75, 82, 61, 75],
         [84, 24,  1, 65]],

        [[ 6, 77, 81, 90],
         [72, 22, 22, 92],
         [88, 62, 93, 94]]], dtype=torch.int32)
tensor(0, dtype=torch.int32) tensor(96, dtype=torch.int32) 0 96


***Concatenate two tensors***

We can concatenate tensors across multiple dimensions, like stacking the dimensions

In [3]:
x = (torch.rand(2,3,4)*100).int()
y = (torch.rand(2,3,4)*100).int()

print(x)
print(y)

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]]], dtype=torch.int32)
tensor([[[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)


In [4]:
def_cat = torch.cat((x,y)) #Creates a tensor of size 4x3x4 after concatenating at the default dimension dim=0
def_cat

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]],

        [[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)

In [8]:
cat_1 = torch.cat((x,y),dim=1) #Creates a tensor of size 2x6x4 after concatenating at dim=1
cat_2 = torch.cat((x,y),2) #Creates a tensor of size 2x6x4 after concatenating at dim=2
print(cat_1)
print(cat_2)


tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13],
         [17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96],
         [73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)
tensor([[[41, 17, 79, 74, 17,  7, 51, 20],
         [11, 16, 89, 84, 89, 41,  8, 81],
         [71, 52, 20, 13, 24, 81, 40, 92]],

        [[19, 65, 48, 11, 73, 15, 39, 71],
         [34, 77, 17, 62, 67, 19, 91, 20],
         [41, 15, 66, 96, 34, 38, 19, 12]]], dtype=torch.int32)
