# **Pytorch Basics**

It is a Python based scitific computing package targeted at 2 sets of audiences-
 

1.   A replacement for Numpy to use the power of GPUs
2.   A deep learning research platform that provides maximum flexibility and speed.




**What is a Tensor?**

This is the basic element in Pytorch.
It is similar to Numpy ndarray, with the additional capability to be used on a GPU to speed up computing.


In [34]:
import torch
print(torch.__version__)

1.4.0


# **Creating tensors**


***Empty/Uninitialized Tensor***

Creating empty placeholder tensors -uninitialized tensors. An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values. 
Also, an empty tensor can be created using empty_like() which creates a tensor with size similar to provided tensor.

In [39]:
x0 = torch.empty((2,3)) #Creates an uninitialized tensor of size 2,3. Provide "dtype" arg to have data of certain type, 
print(x0)                    #and "device" for CPU or current CUDA device. Default is CPU. 

x1 = torch.empty_like(x0) #Creates an uninitialized tensor of size same as tensor x0. 
print(x1)

print(x0.dtype)
x0_like = torch.empty_like(x0,dtype=torch.int) #Provide other args to override the settings of x0.
print(x0_like, x0_like.dtype)

x0_new = x0.new_empty((2,2)) #Creates a tensor with size mentioned but has the same dtype and device settings of x0.
print(x0_new, x0.dtype, x0_new.dtype)


tensor([[5.3231e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.6675e-43]])
tensor([[5.3232e-37, 0.0000e+00, 4.2039e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
torch.float32
tensor([[53813888,        0,        3],
        [       0,        1,        0]], dtype=torch.int32) torch.int32
tensor([[5.3231e-37, 0.0000e+00],
        [4.2039e-45, 0.0000e+00]]) torch.float32 torch.float32


***Zeros/Ones initialized tensor***

Tensors can be initialized to zeros or ones too.

In [42]:
z0 = torch.zeros((2,3)) #Creates a 2x3 tensor initialised with float 0s as tensor.float is the default data type for tensor in Pytorch
print(z0)

z1 = torch.zeros_like(z0, dtype=torch.int) #Creates a tensor of 0s of size same as z0 - 2x3
print(z1, z1.shape)

z2 = z1.new_zeros((2,2)) #Creates a tensor of 0s of size 2x2, but with same dtype and device settings of z1.
print(z2, z2.dtype)


o0 = torch.ones((2,3)) #Creates a 2x3 tensor initialised with float 1s as tensor.float is the default data type for tensor in Pytorch
print(o0)

o1 = torch.ones_like(o0, dtype=torch.int) #Creates a tensor of 1s of size same as o0 - 2x3
print(o1, o1.shape)

o2 = o1.new_ones((2,2)) #Creates a tensor of 1s of size 2x2, but with same dtype and device settings of o1.
print(o2, o2.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32) torch.Size([2, 3])
tensor([[0, 0],
        [0, 0]], dtype=torch.int32) torch.int32
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32) torch.Size([2, 3])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32) torch.int32


***Randomly Initialized Tensor***

The random initialization is done with random numbers from uniform distribution with interval between 0 and 1.

In [23]:
r0 = torch.rand(4) #Since only 1 dimension is mentioned i.e 4, it creates a tensor of rank 1 or a 1 dimensional tensor.
print(r0, r0.shape, r0.size())

r1 = torch.rand((1,4)) #Since 1,4 is provided, it creates a tensor of rank 2 or a 2 dimensional tensor.
print(r1, r1.shape, r1.size())

r2 = torch.rand((2,3))
print(r2, r2.shape, r2.size())

r3 = torch.rand_like(r1) #Creates a tensor of same size as r1 but with its own random values.
print(r3, r3.shape, r3.size())


tensor([0.2696, 0.6186, 0.9954, 0.7714]) torch.Size([4]) torch.Size([4])
tensor([[0.0468, 0.7015, 0.3237, 0.3843]]) torch.Size([1, 4]) torch.Size([1, 4])
tensor([[0.2095, 0.1279, 0.9561],
        [0.9771, 0.3121, 0.6772]]) torch.Size([2, 3]) torch.Size([2, 3])
tensor([[0.0528, 0.1585, 0.3900, 0.0870]]) torch.Size([1, 4]) torch.Size([1, 4])


***Data initialized tensor***

Initialize a tensor with data while creating it.

In [47]:
t0 = torch.tensor([[1,2,3],[4,5,6]]) #Creates a tensor with mentioned data of the size as in data.
print(t0, t0.dtype)

t1 = t0.new_tensor([[1.0,2.0],[3,4],[5,6]]) #Creates a tensor with mentioned data but with dtype and device as t0
print(t1, t0.dtype, t1.dtype)



tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64
tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.int64 torch.int64


Since .size() operation or shape attribute return a tuple, we can perform  operations of tuple in order to get the rank of the tensor or the number of dimensions or values of dimensions.

In [49]:
print("Rank of tensors r0 and r1:", len(r0.shape), len(r1.shape)) #Also can be performed on .size() method
print("1st dimension of r0 and r1:",r0.shape[0], r1.shape[0])
print("2nd dimension of r0 and r1:",r0.shape[1], r1.shape[1]) #Throws IndexError as there is no 2nd dimension for r0, as it is a rank1 tensor.

Rank of tensors r0 and r1: 1 2
1st dimension of r0 and r1: 4 1


IndexError: ignored