# **Pytorch Operations**

Accessing the tensor data, slicing it, editing the data and performing various mathematical operations on it.


In [2]:
import torch
print(torch.__version__)

1.4.0


***Casting PyTorch tensor to another type***

By default PyTorch tensors are FloatTensors. Having said that, we can convert/cast the tensors between various types.

In [13]:
def_tensor = torch.rand((2,3)) # By default, Pytorch tensors are FloatTensor. torch.Tensor is an alias for the default tensor type (torch.FloatTensor).
print(def_tensor)
print(type(def_tensor))

int_def_tensor = def_tensor.int() #Casts float tensor to int using int(), but we are losing information here.
print(int_def_tensor)

int_def_tensor = (def_tensor*100).int() #Multiply the tensor with 100, gets us some data,, and then when we cast it to int(),, we still have some info.
print(int_def_tensor)

tensor([[0.7585, 0.4014, 0.2297],
        [0.8760, 0.6446, 0.4661]])
<class 'torch.Tensor'>
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[75, 40, 22],
        [87, 64, 46]], dtype=torch.int32)


torch.Tensor

***Concatenate two tensors***

We can concatenate tensors across multiple dimensions, like stacking the dimensions

In [3]:
x = (torch.rand(2,3,4)*100).int()
y = (torch.rand(2,3,4)*100).int()

print(x)
print(y)

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]]], dtype=torch.int32)
tensor([[[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)


In [4]:
def_cat = torch.cat((x,y)) #Creates a tensor of size 4x3x4 after concatenating at the default dimension dim=0
def_cat

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]],

        [[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)

In [8]:
cat_1 = torch.cat((x,y),dim=1) #Creates a tensor of size 2x6x4 after concatenating at dim=1
cat_2 = torch.cat((x,y),2) #Creates a tensor of size 2x6x4 after concatenating at dim=2
print(cat_1)
print(cat_2)


tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13],
         [17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96],
         [73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)
tensor([[[41, 17, 79, 74, 17,  7, 51, 20],
         [11, 16, 89, 84, 89, 41,  8, 81],
         [71, 52, 20, 13, 24, 81, 40, 92]],

        [[19, 65, 48, 11, 73, 15, 39, 71],
         [34, 77, 17, 62, 67, 19, 91, 20],
         [41, 15, 66, 96, 34, 38, 19, 12]]], dtype=torch.int32)
