# **Pytorch Operations**

Accessing the tensor data, slicing it, editing the data and performing various mathematical operations on it.


In [2]:
import torch
print(torch.__version__)

1.4.0


***Concatenate two tensors***

We can concatenate tensors across the multiple dimensions

In [3]:
x = (torch.rand(2,3,4)*100).int()
y = (torch.rand(2,3,4)*100).int()

print(x)
print(y)

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]]], dtype=torch.int32)
tensor([[[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)


In [4]:
def_cat = torch.cat((x,y)) #Creates a tensor of 4x3x4 after concatenating at dim=0
def_cat

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96]],

        [[17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)

In [5]:
cat_1 = torch.cat((x,y),dim=1)
cat_1

tensor([[[41, 17, 79, 74],
         [11, 16, 89, 84],
         [71, 52, 20, 13],
         [17,  7, 51, 20],
         [89, 41,  8, 81],
         [24, 81, 40, 92]],

        [[19, 65, 48, 11],
         [34, 77, 17, 62],
         [41, 15, 66, 96],
         [73, 15, 39, 71],
         [67, 19, 91, 20],
         [34, 38, 19, 12]]], dtype=torch.int32)

In [6]:
cat_2 = torch.cat((x,y),2)
cat_2

tensor([[[41, 17, 79, 74, 17,  7, 51, 20],
         [11, 16, 89, 84, 89, 41,  8, 81],
         [71, 52, 20, 13, 24, 81, 40, 92]],

        [[19, 65, 48, 11, 73, 15, 39, 71],
         [34, 77, 17, 62, 67, 19, 91, 20],
         [41, 15, 66, 96, 34, 38, 19, 12]]], dtype=torch.int32)